---
- name: "Chrome.yml"
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: (chrome) google chrome add key
      apt_key:
        url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
        state: present

    - name: (chrome) google chrome add repository
      apt_repository:
        repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
        filename: "google-chrome"
        state: present
        update_cache: yes

    - name: (chrome) install browser
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - chromium
          - chromium-l10n
          - google-chrome-beta
          - google-chrome-stable
